import { Company, Branch, Employee, TimeEntry } from '../types';

export const demoCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'TechCorp Nederland BV',
    kvk: '12345678',
    taxNumber: 'NL001234567B01',
    address: {
      street: 'Techniekstraat 123',
      city: 'Amsterdam',
      zipCode: '1000 AA',
      country: 'Nederland',
    },
    contactInfo: {
      email: 'info@techcorp.nl',
      phone: '+31 20 1234567',
      website: 'https://techcorp.nl',
    },
    settings: {
      defaultCAO: 'CAO ICT',
      travelAllowancePerKm: 0.23,
      standardWorkWeek: 40,
      holidayAllowancePercentage: 8,
      pensionContributionPercentage: 18.5,
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'comp-2',
    name: 'BuildMax Constructie BV',
    kvk: '87654321',
    taxNumber: 'NL009876543B01',
    address: {
      street: 'Bouwersweg 456',
      city: 'Rotterdam',
      zipCode: '3000 BB',
      country: 'Nederland',
    },
    contactInfo: {
      email: 'hr@buildmax.nl',
      phone: '+31 10 7654321',
      website: 'https://buildmax.nl',
    },
    settings: {
      defaultCAO: 'CAO Bouw',
      travelAllowancePerKm: 0.25,
      standardWorkWeek: 40,
      holidayAllowancePercentage: 8,
      pensionContributionPercentage: 20,
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-12-10'),
  },
];

export const demoBranches: Branch[] = [
  {
    id: 'branch-1',
    companyId: 'comp-1',
    name: 'Hoofdkantoor Amsterdam',
    location: 'Amsterdam Centrum',
    costCenter: 'CC-001',
    cao: 'CAO ICT',
    specificSettings: {
      overtimeRate: 150,
      irregularRate: 130,
      shiftRate: 120,
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'branch-2',
    companyId: 'comp-1',
    name: 'Vestiging Utrecht',
    location: 'Utrecht Science Park',
    costCenter: 'CC-002',
    cao: 'CAO ICT',
    specificSettings: {
      overtimeRate: 150,
      irregularRate: 125,
      shiftRate: 115,
    },
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'branch-3',
    companyId: 'comp-2',
    name: 'Bouwplaats Rotterdam',
    location: 'Rotterdam Haven',
    costCenter: 'BC-001',
    cao: 'CAO Bouw',
    specificSettings: {
      overtimeRate: 150,
      irregularRate: 140,
      shiftRate: 125,
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-12-05'),
  },
];

export const demoEmployees: Employee[] = [
  {
    id: 'emp-1',
    companyId: 'comp-1',
    branchId: 'branch-1',
    personalInfo: {
      firstName: 'Jan',
      lastName: 'van der Berg',
      bsn: '123456789',
      dateOfBirth: new Date('1985-06-15'),
      address: {
        street: 'Keizersgracht 123',
        city: 'Amsterdam',
        zipCode: '1015 CJ',
        country: 'Nederland',
      },
      contactInfo: {
        email: 'j.vandenberg@techcorp.nl',
        phone: '+31 6 12345678',
      },
      bankAccount: 'NL91 ABNA 0417 1643 00',
    },
    contractInfo: {
      type: 'permanent',
      startDate: new Date('2024-01-15'),
      hoursPerWeek: 40,
      position: 'Senior Software Developer',
    },
    salaryInfo: {
      salaryScale: 'D',
      hourlyRate: 45,
      allowances: {
        overtime: 150,
        irregular: 130,
        shift: 120,
        weekend: 150,
      },
      holidayAllowancePercentage: 8,
      travelAllowancePerKm: 0.23,
      pensionContribution: 5.5,
    },
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-15'),
  },
  {
    id: 'emp-2',
    companyId: 'comp-1',
    branchId: 'branch-1',
    personalInfo: {
      firstName: 'Maria',
      lastName: 'Gonzalez',
      bsn: '987654321',
      dateOfBirth: new Date('1990-03-22'),
      address: {
        street: 'Prinsengracht 456',
        city: 'Amsterdam',
        zipCode: '1016 HH',
        country: 'Nederland',
      },
      contactInfo: {
        email: 'm.gonzalez@techcorp.nl',
        phone: '+31 6 98765432',
      },
      bankAccount: 'NL82 INGB 0002 4455 66',
    },
    contractInfo: {
      type: 'permanent',
      startDate: new Date('2024-03-01'),
      hoursPerWeek: 32,
      position: 'UX Designer',
    },
    salaryInfo: {
      salaryScale: 'C',
      hourlyRate: 38,
      allowances: {
        overtime: 150,
        irregular: 125,
        shift: 115,
        weekend: 150,
      },
      holidayAllowancePercentage: 8,
      travelAllowancePerKm: 0.23,
      pensionContribution: 5.5,
    },
    status: 'active',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 'emp-3',
    companyId: 'comp-2',
    branchId: 'branch-3',
    personalInfo: {
      firstName: 'Piet',
      lastName: 'Jansen',
      bsn: '456789123',
      dateOfBirth: new Date('1978-11-08'),
      address: {
        street: 'Maasstraat 789',
        city: 'Rotterdam',
        zipCode: '3011 NK',
        country: 'Nederland',
      },
      contactInfo: {
        email: 'p.jansen@buildmax.nl',
        phone: '+31 6 45678912',
      },
      bankAccount: 'NL73 RABO 0123 4567 89',
    },
    contractInfo: {
      type: 'permanent',
      startDate: new Date('2024-02-01'),
      hoursPerWeek: 40,
      position: 'Projectleider Bouw',
    },
    salaryInfo: {
      salaryScale: 'E',
      hourlyRate: 52,
      allowances: {
        overtime: 150,
        irregular: 140,
        shift: 125,
        weekend: 150,
      },
      holidayAllowancePercentage: 8,
      travelAllowancePerKm: 0.25,
      pensionContribution: 6,
    },
    status: 'active',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-12-01'),
  },
];

export const demoTimeEntries: TimeEntry[] = [
  {
    id: 'time-1',
    employeeId: 'emp-1',
    date: new Date('2024-12-16'),
    regularHours: 8,
    overtimeHours: 2,
    irregularHours: 0,
    travelKilometers: 25,
    project: 'Website Redesign',
    branchId: 'branch-1',
    status: 'approved',
    createdAt: new Date('2024-12-16'),
    updatedAt: new Date('2024-12-16'),
  },
  {
    id: 'time-2',
    employeeId: 'emp-2',
    date: new Date('2024-12-16'),
    regularHours: 6.4,
    overtimeHours: 0,
    irregularHours: 0,
    travelKilometers: 15,
    project: 'Mobile App UX',
    branchId: 'branch-1',
    status: 'approved',
    createdAt: new Date('2024-12-16'),
    updatedAt: new Date('2024-12-16'),
  },
  {
    id: 'time-3',
    employeeId: 'emp-3',
    date: new Date('2024-12-16'),
    regularHours: 8,
    overtimeHours: 0,
    irregularHours: 4,
    travelKilometers: 45,
    project: 'Kantoorgebouw Centrum',
    branchId: 'branch-3',
    status: 'draft',
    createdAt: new Date('2024-12-16'),
    updatedAt: new Date('2024-12-16'),
  },
];